### ISSUE TITLE
enoent on OTP 25

### ISSUE THREAD

**Issue by tsloughter** [g-andrade/tls_certificate_check#37]
This issue on OTP-25 has come up for us a few times, https://github.com/open-telemetry/opentelemetry-erlang/issues/545

`pubkey_os_cacerts:get/0` is failing with `enoent` for some reason. Have you seen this at all? Does there just need to be some error handling there to fallback to pre-OTP-25 behaviour if it fails?

**Comment by g-andrade** [comment]
Ah! My mistake... It looks like the following is happening:

1. `pubkey_os_cacerts:load/0` returns an error, resulting in a bad match:
https://github.com/erlang/otp/blob/07cf1c5caab19852ccf85ae7000d788913f3411d/lib/public_key/src/pubkey_os_cacerts.erl#L38
2. `tls_certificate_check:maybe_load_authorities_trusted_by_otp/3` fails to catch the exception because it's matching anything that's both not of the `error` class nor for an `undef` reason, rather than _neither_:
https://github.com/g-andrade/tls_certificate_check/blob/93bfba794fe55c1b7fb8ee3d410311c1f870d079/src/tls_certificate_check_shared_state.erl#L372

**Comment by g-andrade** [comment]
I've reproduced the issue and applied a fix: `tls_certificate_check` 1.17.4 should work as expected. Thanks for reporting!
